### ISSUE TITLE
Tracking issue for update to Cranelift 0.91

### ISSUE THREAD

**Issue by bjorn3** [bjorn3/rustc_codegen_cranelift#1307]
# Blocking issues

* [x] https://github.com/bytecodealliance/wasmtime/issues/5425 (https://github.com/bytecodealliance/wasmtime/pull/5442)
* [x] Release Cranelift 0.91 (https://github.com/bytecodealliance/wasmtime/pull/5478)

# Api changes

* [x] https://github.com/bytecodealliance/wasmtime/pull/5196
* [x] https://github.com/bytecodealliance/wasmtime/pull/5316

# New features

* [x] https://github.com/bytecodealliance/wasmtime/pull/5353 (fixes https://github.com/bjorn3/rustc_codegen_cranelift/issues/661)
* [ ] https://github.com/bytecodealliance/wasmtime/pull/5285

Branch: https://github.com/bjorn3/rustc_codegen_cranelift/tree/update_cranelift
