### ISSUE TITLE
Tracking issue for update to Cranelift 0.93

### ISSUE THREAD

**Issue by bjorn3** [bjorn3/rustc_codegen_cranelift#1352]
# Blocking issues

* [x] https://github.com/bytecodealliance/wasmtime/issues/5716
* [x] https://github.com/bytecodealliance/wasmtime/issues/5711

# Api changes

* [x] https://github.com/bytecodealliance/wasmtime/pull/5464
* [x] https://github.com/bytecodealliance/wasmtime/pull/5630

# New features

* https://github.com/bytecodealliance/wasmtime/pull/5587
* [x] https://github.com/bytecodealliance/wasmtime/pull/5627

Branch: https://github.com/bjorn3/rustc_codegen_cranelift/tree/update_cranelift
