### ISSUE TITLE
Remove the need for core/std patches

### ISSUE THREAD

**Issue by bjorn3** [bjorn3/rustc_codegen_cranelift#337]
* [x] 0001-Disable-stdsimd.patch (8c2577c74731688ccc2d59ed92e8d334735c673c removed patch, but doesn't fix stdsimd) (assumes llvm intrinsics, https://github.com/bjorn3/rustc_codegen_cranelift/issues/171)
* [x] 0002-Disable-u128-and-i128-in-libcore.patch (blocked on https://github.com/CraneStation/cranelift/issues/354) (mostly removed in 57feadcc13bbf32c599e79c811162f576de0efd1 by letting u128 and i128 taking or returning function trap, more removed in 8506784d74603ddbe3e37aeb4f9191afc28b5205)
* [x] 0003-Disable-inline-assembly-in-hint-spin_loop.patch <strike>(inline assembly, should probably become an intrinsic)</strike> (1e074106e60e6b3108c7757a70c1e72be385d3ba)
* [x] 0006-alloc-Disable-some-unsupported-stuff.patch <strike>(blocked on https://github.com/CraneStation/cranelift/issues/354)</strike> (e09ae252992acb2d646e8f749d92752fac5f85c6)
* [x] 0009-Workaround-missing-saturating_sub-intrinsic-impl.patch <strike>(blocked on #1)</strike> (???)
* [x] 0011-Workaround-for-libstd-crash.patch (05307af6729a9df0375f063c4b2417366057e058)
* [x] 0013-Patch-away-bswap-usage.patch <strike>(blocked on #1)</strike> (db5ffdedf7ed64bde30a55e14e67efbb0f6ea538)
* [x] 0014-Don-t-use-OS-TLS.patch (05307af6729a9df0375f063c4b2417366057e058)
* [x] 0015-Remove-usage-of-unsized-locals.patch <strike>(blocked on #15)</strike> (dcc86d306c28dc1b35e0d9b1370751da7689023a)
* [x] 0016-Disable-cpuid-intrinsic.patch (blocked on implementing x86 intrinsic `cpuid`) (#1070)
* [x] 0017-Fix-libtest-compilation.patch <strike>(blocked on #15)</strike> (dcc86d306c28dc1b35e0d9b1370751da7689023a and c5b5b2b702f9d2847e088d0e9e73fea1914793c5)
* [x] 0018-test-Force-single-thread-mode.patch <strike>(blocked on #388)</strike>
* [ ] 0022-core-Disable-not-compiling-tests.patch (blocked on #806)
* [ ] 0023-core-Ignore-failing-tests.patch (blocked on #806)
* [x] 0024-libstd-Revert-arg-initialization-on-linux-to-not-req.patch <strike>(blocked on implementing `#[link_section]`)</strike> (5c6bf836fe3d4cfda1b827a5cd3982e5a588c0ff)
* [x] 0025-Remove-usage-of-extern_weak-in-thread_local_dtor.patch (#1074)

**Comment by bjorn3** [comment]
The only remaining patches are for tests in libcore.
