### ISSUE TITLE
Enable mir inlining by default

### ISSUE THREAD

**Issue by bjorn3** [bjorn3/rustc_codegen_cranelift#805]
Blocked on:

* [x] <strike>rust-lang/rust#63802</strike>
* [x] <strike>rust-lang/rust#66345</strike>
* [x] <strike>rust-lang/rust#67529</strike>
* [x] <strike>maybe rust-lang/rust#67550</strike>
* [x] <strike>maybe rust-lang/rust#68841</strike>
* [ ] https://github.com/rust-lang/rust/issues/81567 is the upstream tracking issue for enabling the mir inliner

Cranelift doesn't have any inlining support itself.

Edit(2019-12-23): Added more blocking issues
Edit(2021-01-31): Added upstream tracking issue

**Comment by bjorn3** [comment]
https://github.com/bjorn3/rustc_codegen_cranelift/commit/84f24e530a0f2359916db4b6e2f47ca52df42994 re-enables mir inlining again for libstd. This resulted in a perf improvement of about 30% on simple-raytracer.

**Comment by bjorn3** [comment]
Since https://github.com/rust-lang/rust/pull/91743 the MIR inliner is enabled by default in release mode. Given that the optimized MIR is stored in the crate metadata, having the standard library compiled with MIR inlining enabled benefits even debug mode user programs.
